version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "17:30"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
    assignees:
      - dev01d

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "17:30"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
    assignees:
      - dev01d
