name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
          check-latest: true

      - name: Install dependencies
        run: yarn install

      - name: Publish theme
        run: yarn deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
