name: Release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Build theme
        run: yarn build

      - name: Release theme to VSCode market
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: yarn release

      - name: Release theme to Open VSX market
        env:
          OPEN_VSX_TOKEN: ${{ secrets.OPEN_VSX_TOKEN }}
        run: yarn release-ovsx
